export type Polo = {
  value: string;
  label: number;
};

export const polos: Polo[] = [
  { value: "AC-Rio Branco", label: 3599 },
  { value: "AC-Sena Madureira", label: 1783 },
  { value: "AL-Maceió", label: 22868 },
  { value: "AM-Humaitá", label: 2179 },
  { value: "AM-Itacoatiara", label: 2445 },
  { value: "AM-Manaus", label: 25410 },
  { value: "AM-Parintins", label: 2346 },
  { value: "AM-Tabatinga", label: 1862 },
  { value: "AP-Macapá", label: 10795 },
  { value: "BA-Alagoinhas", label: 3490 },
  { value: "BA-Barreiras", label: 5302 },
  { value: "BA-Feira de Santana", label: 18307 },
  { value: "BA-Itabuna", label: 8314 },
  { value: "BA-Salvador e Região Metropolitana", label: 42991 },
  { value: "BA-Senhor do Bonfim", label: 6678 },
  { value: "BA-Teixeira de Freitas", label: 2459 },
  { value: "BA-Vitória da Conquista", label: 9619 },
  { value: "CE-Fortaleza", label: 27643 },
  { value: "CE-Juazeiro do Norte", label: 8704 },
  { value: "CE-Quixadá", label: 2789 },
  { value: "CE-Sobral", label: 6753 },
  { value: "DF-Brasília", label: 63953 },
  { value: "DF-DF (Entorno)", label: 12979 },
  { value: "ES-Cachoeiro de Itapemirim", label: 2477 },
  { value: "ES-Colatina", label: 2734 },
  { value: "ES-Vitória", label: 9095 },
  { value: "GO-Anápolis", label: 4620 },
  { value: "GO-Goiânia", label: 15944 },
  { value: "GO-Itumbiara", label: 2220 },
  { value: "GO-Rio Verde", label: 2925 },
  { value: "GO-Uruaçu", label: 4009 },
  { value: "MA-Bacabal", label: 9747 },
  { value: "MA-Imperatriz", label: 7631 },
  { value: "MA-São Luís", label: 30722 },
  { value: "MG-Belo Horizonte", label: 30722 },
  { value: "MG-Governador Valadares", label: 4602 },
  { value: "MG-João Pinheiro", label: 1433 },
  { value: "MG-Montes Claros", label: 6662 },
  { value: "MG-Sudeste", label: 11353 },
  { value: "MG-Teófilo Otoni", label: 2329 },
  { value: "MG-Triângulo Mineiro", label: 7818 },
  { value: "MG-Varginha", label: 8208 },
  { value: "MS-Campo Grande", label: 6315 },
  { value: "MS-Corumbá", label: 995 },
  { value: "MS-Dourados", label: 2777 },
  { value: "MS-Três Lagoas", label: 1204 },
  { value: "MT-Cáceres", label: 2290 },
  { value: "MT-Cuiabá", label: 6829 },
  { value: "MT-Rondonópolis", label: 3350 },
  { value: "MT-Sinop", label: 3247 },
  { value: "PA-Belém", label: 33977 },
  { value: "PA-Cametá", label: 11543 },
  { value: "PA-Castanhal", label: 12172 },
  { value: "PA-Itaituba", label: 1132 },
  { value: "PA-Marabá", label: 8285 },
  { value: "PA-Santarém", label: 8483 },
  { value: "PB-Campina Grande", label: 5759 },
  { value: "PB-João Pessoa", label: 9356 },
  { value: "PB-Patos", label: 5885 },
  { value: "PE-Caruaru", label: 25386 },
  { value: "PE-Petrolina", label: 10240 },
  { value: "PE-Recife", label: 37020 },
  { value: "PI-Picos", label: 7459 },
  { value: "PI-Teresina", label: 12392 },
  { value: "PR-Centro", label: 4879 },
  { value: "PR-Curitiba", label: 18316 },
  { value: "PR-Noroeste", label: 7160 },
  { value: "PR-Norte", label: 7205 },
  { value: "PR-Oeste", label: 6545 },
  { value: "PR-Região Metropolitana", label: 4475 },
  { value: "RJ-Costa Verde", label: 1316 },
  { value: "RJ-Metropolitana", label: 30267 },
  { value: "RJ-Norte Fluminense", label: 11598 },
  { value: "RJ-Rio de Janeiro (capital)", label: 54852 },
  { value: "RJ-Sul Fluminense", label: 7910 },
  { value: "RN-Mossoró", label: 5369 },
  { value: "RN-Natal", label: 15089 },
  { value: "RO-Cacoal", label: 3335 },
  { value: "RO-Porto Velho", label: 5557 },
  { value: "RR-Boa Vista", label: 4704 },
  { value: "RS-Caxias do Sul", label: 7903 },
  { value: "RS-Passo Fundo", label: 5020 },
  { value: "RS-Pelotas", label: 5257 },
  { value: "RS-Porto Alegre (Região Metropolitana)", label: 16126 },
  { value: "RS-Santa Maria", label: 6649 },
  { value: "SC-Blumenau", label: 7177 },
  { value: "SC-Chapecó", label: 2061 },
  { value: "SC-Criciúma", label: 2671 },
  { value: "SC-Florianópolis", label: 7735 },
  { value: "SC-Lages", label: 1081 },
  { value: "SE-Aracaju", label: 15188 },
  { value: "SP-ABC", label: 6104 },
  { value: "SP-Baixada Santista", label: 5266 },
  { value: "SP-Bauru/Assis/Marília/Ourinhos", label: 7274 },
  { value: "SP-Campinas/Jundiaí/Sorocaba", label: 13735 },
  { value: "SP-Guarulhos/Leste", label: 13141 },
  { value: "SP-Itapevi/Itapetinga", label: 1966 },
  { value: "SP-Osasco", label: 9089 },
  { value: "SP-Piracicaba/Botucatu/Jaú", label: 4565 },
  { value: "SP-Presidente Prudente", label: 4161 },
  { value: "SP-Ribeirão Preto", label: 10161 },
  { value: "SP-São José do Rio Preto/Araçatuba", label: 6127 },
  { value: "SP-São Paulo (capital)", label: 38437 },
  { value: "SP-Sul Santo Amaro", label: 6001 },
  { value: "SP-Vale do Paraíba", label: 6808 },
  { value: "TO-Araguaína", label: 6808 },
  { value: "TO-Palmas", label: 3988 },
];
